###### for routing.js
GET http://localhost:3000/all/data

###
POST http://localhost:3000/all
Content-Type: application/json

{
  "name": "Pedro",
  "type": "normal",
  "moves": [
    "Transform"
  ]
}

### 
POST http://localhost:3000/other
Content-Type: application/json

#######
####### for movies-local.js and movies-mysql.js
#for ./web/index.html use npx servor ./web
GET http://localhost:3000/

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies?genre=crime

###
GET http://localhost:3000/movies/213241c1-1ff1-11f0-964c-c45444d093a2

###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Salute",
  "year": 2022,
  "director": "Juan M.",
  "duration": 163,
  "poster": "https://m.media-amazon.com/images/I/91obuWzA3XL._AC_UF1000,1000_QL80_.jpg",
  "genre": [
    "Comedy",
    "Drama",
    "Adventure"
  ],
  "rate": 9.6
}

###
PATCH http://localhost:3000/movies/213241c1-1ff1-11f0-964c-c45444d093a2
Content-Type: application/json

{
  "title": "Deleted all movies",
  "genre": [
    "Thriller",
    "Fantasy",
    "Comedy"
  ]
}

###
DELETE http://localhost:3000/movies/d6338363-1f8e-11f0-964c-c45444d093a2

###
GET http://localhost:3000/movies