GET http://localhost:3000/all/data

###
POST http://localhost:3000/all
Content-Type: application/json

{
  "name": "Pedro",
  "type": "normal",
  "moves": [
    "Transform"
  ]
}

###
GET http://localhost:3000/

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies?genre=crime

###
GET http://localhost:3000/movies/618fed5b-1f2e-11f0-964c-c45444d093a2

###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Warcraft",
  "year": 2016,
  "director": "Duncan Jones",
  "duration": 163,
  "poster": "https://m.media-amazon.com/images/I/91obuWzA3XL._AC_UF1000,1000_QL80_.jpg",
  "genre": [
    "Adventure",
    "Drama",
    "Sci-Fi"
  ],
  "rate": 8.6
}

###
PATCH http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
  "title": "ThreeCamp",
  "year": 2012
}

###
DELETE http://localhost:3000/movies/11497de0-dbdd-405d-958b-86357b9bd452
